/// <reference types="react-scripts" />
type User = {
  "id": number,
  "name": string,
  "surname": string,
  "link": string,
  "image_url": string
};

type Competitor = {
  "user": User,
  "org": {
    "image_url": string,
    "title": string,
    "link": string,
    "id": number
  },
  "coach_one": Coach | null,
  "coach_two": Coach | null,
};

type Coach = {
  "id": number,
  "link": string,
  "name": string,
  "surname": string,
  "followers_count": number,
  "mini_image_url": string,
  "place_id": number
}

type Pair = {
  "id": number,
  "event_id": number,
  "division_id": number,
  "group_id": number,
  "category_id": number,
  "sp1_id": number,
  "sp2_id": number,
  "leftId": number,
  "rightId": number,
  "winner_id": number,
  "score_one": number,
  "score_two": number,
  "winner_n": number,
  "is_final": number,
  "serial": number,
  "win_type_id": number,
  "number": number,
  "type": number,
  "tp_score_one": number,
  "tp_score_two": number,
  "p1_score_one": number,
  "p2_score_one": number,
  "p3_score_one": number,
  "p1_score_two": number,
  "p2_score_two": number,
  "p3_score_two": number,
  "j1_score_one": number,
  "j2_score_one": number,
  "j3_score_one": number,
  "j4_score_one": number,
  "j1_score_two": number,
  "j2_score_two": number,
  "j3_score_two": number,
  "j4_score_two": number,
  "court": number,
  "warnings_one": number,
  "warnings_two": number,
  "currentRoundTime": string,
  "currentRoundNumber": number,
  "currentRoundType": number,
  "currentRoundStatus": number,
  "lastStartTime": string,
  "is_finished": number,
  "faultsOne": number,
  "faultsTwo": number,
  "is_active": number,
  "day": number,
  "set_score_time": number,
  "place": number,
  "user1"?: Competitor | null | undefined,
  "user2"?: Competitor | null | undefined,
};

type Group = {
  "id": number,
  "event_id": number,
  "division_id": number,
  "title": string,
  "year_from": number,
  "year_to": number,
  "sort_index": number,
  "competitors_count": number,
  "males": number,
  "females": number,
  "mixed": number,
  "category_count": number
};

type Event = {
  "id": number,
  "uid": number,
  "user_id": number,
  "organization_id": number,
  "federation_id": number,
  "title": string,
  "date_from": string,
  "date_to": string,
  "date_deadline": string,
  "last_registration_date": string,
  "description": string
  "country_id": number,
  "region_id": number,
  "town_id": number,
  "address": string,
  "mark": number,
  "code": string,
  "level": number,
  "courts": number,
  "days": number,
  "deadline": number,
  "googleLat": number,
  "googleLng": number,
  "head_judge": string,
  "head_secretary": string,
  "image_url": string
  "mini_image_url": string
  "background_url": string,
  "logo_url": string,
  "canReg": number,
  "isBlocked": number,
  "creation_time": number,
  "sport_id": number,
  "type_id": number,
  "status": number,
  "files_count": number,
  "protocol_type": number,
  "open_reg": number,
  "show_results": number,
  "hide_event": number,
  "can_edit": number,
  "access_level": number,
  "license_type": number,
  "members_count": number,
  "latitude": number,
  "longitude": number,
  "trainers": number,
  "sportsmans": number,
  "judges": number,
  "organizations": number,
  "countries": number,
  "teams": number,
  "official": number,
  "representatives": number,
  "volunteers": number,
  "medicals": number,
  "media": number,
  "link": string,
  "contacts": string,
  "limited": number,
  "calendar_events": number,
  "email": string,
  "phone": string,
  "phone2": string,
  "website_link": string,
  "facebook_link": string,
  "instagram_link": string,
  "time_from": number,
  "time_to": number,
  "address_comp": string,
  "place_id": string,
  "views": number,
  "participating_type": number,
  "followers": number,
  "address2": string,
  "with_referee": number,
  "renumber_type": number,
  "show_event": number,
  "show_registration": number,
  "live_links": number,
  "cr": number,
  "currency_code": string,
  "last_live_start": number,
  "price": number,
  "reg_method": number,
  "max_channels": number,
  "streams": number,
  "rooms": number,
  "reg_room": number,
  "reg_form_id": number,
  "is_virtual": number,
  "hasSingle": number,
  "hasTeams": number,
  "created_at": number,
  "location": string
}
